<?php

namespace AppBundle\Repository;

/**
 * ExtrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtrasRepository extends \Doctrine\ORM\EntityRepository
{
}
