<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerB7qtbmx\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerB7qtbmx/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerB7qtbmx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerB7qtbmx\appDevDebugProjectContainer();
